version: '3'
services:
  flyway_clean:
    image: flyway/flyway
    command: -url=jdbc:mysql://db -schemas=kohlantstats -user=root -password=P@ssw0rd -connectRetries=60 clean
    volumes:
      - ./MODEL/migration/src/main/resources/game-score/clean/:/flyway/sql
    depends_on:
      - db
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=P@ssw0rd
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --lower_case_table_names=1
    ports:
      - 3307:3306