version: '3'
services:
  flyway_clean:
   image: flyway/flyway
   command: -url=jdbc:mysql://db -schemas=kohlantstats -user=root -password=P@ssw0rd -connectRetries=60 clean
   volumes:
     - ./MODEL/migration/src/main/resources/game-score/clean/:/flyway/sql
   depends_on:
     - db
  flyway:
    image: flyway/flyway
    command: -url=jdbc:mysql://db -schemas=kohlantstats -user=root -password=P@ssw0rd -connectRetries=60 migrate
    volumes:
      - ./MODEL/migration/src/main/resources/game-score/migration/:/flyway/sql
    depends_on:
      - flyway_clean
  db:
 #   image: mysql_8_0
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=P@ssw0rd
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --lower_case_table_names=1
    ports:
      - 3307:3306

  web:
    image: tomcat:latest
    #image: tomcat:8.0
    ##TODO add context.xml with jndi embedded into META-INF/ dir
    ##TODO add remove jdk11 dep en EE libs
    # Environment variables do not appear to be getting loaded the first time Tomcat starts!
    environment:
      JDBC_URL: jdbc:mysql://db:3306/kohlantstats?connectTimeout=0&amp;socketTimeout=0&amp;autoReconnect=true
      JDBC_USER: root
      JDBC_PASS: P@ssw0rd
    ports:
    - "80:8080"
    volumes:
    - ./APPS/__RELEASES/tomcat:/usr/local/tomcat/webapps
   # - ./APPS/__RELEASES/tomcat-conf:/usr/local/tomcat/conf
   # - ./APPS/__RELEASES/tomcat-lib:/usr/local/tomcat/lib
    links:
      - db
    depends_on :
      - flyway
